# Citizens Portal virtual host (included by MAMP PRO httpd.conf)
# Document root: D:/citizens-portal/public

<VirtualHost *:80>
	ServerName citizens-portal.test
	ServerAlias www.citizens-portal.test citizens-id.test www.citizens-id.test
	DocumentRoot "D:/citizens-portal/public"
    <IfModule xsendfile_module>
        XSendFilePath "D:/citizens-portal/public"
    </IfModule>
	<Directory "D:/citizens-portal/public">
		DirectoryIndex index.php
		Options Indexes Includes FollowSymLinks ExecCGI
		AllowOverride All
		Order allow,deny
		Allow from all
	</Directory>
</VirtualHost>

<VirtualHost *:80>
	ServerName citizens-portal.testAtMISO-JP.local
	DocumentRoot "D:/citizens-portal/public"
    <IfModule substitute_module>
        <IfModule headers_module>
            RequestHeader unset Accept-Encoding
        </IfModule>
        Substitute "s|http://citizens-portal.test|http://citizens-portal.testAtMISO-JP.local|ni"
        Substitute "s|https://citizens-portal.test|https://citizens-portal.testAtMISO-JP.local|ni"
    </IfModule>
    <IfModule xsendfile_module>
        XSendFilePath "D:/citizens-portal/public"
    </IfModule>
	<Directory "D:/citizens-portal/public">
		DirectoryIndex index.php
		Options Indexes Includes FollowSymLinks ExecCGI
		AllowOverride All
		Order allow,deny
		Allow from all
	</Directory>
</VirtualHost>
